name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Gradle wrapper
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Display Gradle version
      - name: Display Gradle Version
        run: ./gradlew --version

      # Build the APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Run Unit Tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest